### ISSUE TITLE
add control for dependencies on top of each scripts

### ISSUE THREAD

**Issue by alegrey91** [89luca89/simpler-toolbox#1]
Could be useful to have a check at the beginning of each script to verify the presence of `podman`, etc.
Something similar to this:
```
# Check if the give command is present on the system.
# Arguments:
#   $1 - command name
# Outputs:
#   Notice that the command is not present.
# Examples:
#   check_prerequisite "kubectl"
check_prerequisite () {
    cmd=$1
    if ! command -v "$cmd" &> /dev/null; then
        printf "Please, install $1 first.\n"
        exit 1
    fi
}
```

**Comment by 89luca89** [comment]
I'll add `podman` detection to the create and enter scripts

Init script already does this to install missing dependencies

I'll add a proper one in the export tool as it uses grep sed and systemctl to do stuff

Thanks for the issue
